### ISSUE TITLE
Missing Safe Key in Mission 2: Sven Mynell's Cargo Bay (Normal Difficulty)

### ISSUE THREAD

**Issue by ZTylerDurden** [Xanfre/T2Fix#2]
The key should either be in Mynell's spider den inside a box or drop from a vent in the freezer, depending on the difficulty.  In both instances in T2Fix normal difficulty, the key is missing in both locations.

**Comment by Xanfre** [comment]
My apologies for the very long wait. I was not notified as I should have been.

On normal difficulty, the key should always be in a box in the spider den. T2Fix does not change this, and I cannot replicate this issue either with the release missions or the Thief2 Fixed missions. That said, if you still have a save, I could look into this particular case.

**Comment by ZTylerDurden** [comment]
Apologies as well for the delayed response.

Unfortunately, I overwrote the save.  It's ok though.  I had enough loot from other sources to beat the mission.

**Comment by Xanfre** [comment]
No worries. At the very least, it is good that you were able to continue in spite of this. I will close this issue for now, but feel free to re-open it if you come across this again.
